# This file contains all the configuration our different project components
# Add configurations as needed

training:
  name: vaeTrain
  description: 32*8^3 Latent Space with KL divergence
  experiment_id: fullyConvKL_Weight_1e-3_continue_epoch_45 # None | A unique id identifying the experiment folder
  extra_notes: none
  logs_dir: logs
  is_train: true
  device: cuda:0
  batch_size: 6
  num_workers: 1
  test_size: 0.1
  n_epochs: 500
  append_loss_every: 50
  print_every: 15
  validate_every: 986
  save_every: 1700000000000000000000000000
  save_every_nepochs: 5
  start_epoch: 0
  start_iteration: 0
  visualize_every: 500
  apply_metrics_every: 7400
  load_ckpt: False
  ckpt_path: logs/vaeTrain/fullyConv/2024_05_17_04_07_52/checkpoints/epoch-45.ckpt
  use_scheduler: False
  apply_metrics_batch_count: 5 # number of batches to apply additional metrics on
#2024_05_16_20_23_24 id
dataset:
  dataset_field: shape_net_v3_sdf
  path: src/raw_dataset/ShapeNetV2/sdf_064  # For local testing without downloading shape => change to local_raw_dataset/ShapeNet
    # Can be overriden by dataset specific path
  overfit_size: 64
  split: train # train | valid | test
  is_overfit: False

  shape_net_vox:
    class_filepath: src/datasets/shape_net/shape_net_vox.py
    class: ShapeNetVox
    category: airplane
    path: src/local_raw_dataset/ShapeNet/ShapeNetVox32

  shape_net_points:
    class_filepath: src/datasets/shape_net/shape_net_points.py
    class: ShapeNetPoints
    category: airplane
    path: src/raw_dataset/ShapeNet/ShapeNetPointClouds
  
  shape_net_sdf:
    category: chair
    path: src/raw_dataset/ShapeNetV2/sdf_064
    class_filepath: datasets/shape_net/shape_net_sdf.py
    class: ShapeNetSDF

  shape_net_v2_sdf:
    class_filepath: src/datasets/shape_net/shape_net_v2_sdf.py
    class: ShapeNetV2SDF
    category: chair
    path: src/raw_dataset/ShapeNetCore.v2
  
  shape_net_v3_sdf:
    class_filepath: src/datasets/shape_net/shape_net_v3_sdf.py
    class: ShapeNetV3SDF
    category: chair
    path: src/raw_dataset/ShapeNetDISN/SDF_v1_64

model:
  model_field: vae
  dummy_classifier:
    model_filepath: models/dummy_classifier.py
    model_class: DummyClassifier
    lr: 0.01
    criterion: CE
    scheduler_step_size: 25
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1
  
  auto_encoder:
    model_filepath: src/models/auto_encoder.py
    model_class: AutoEncoder
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    lr: 0.0001
    losses: None
    criterion: MSE
    scheduler_step_size: 300
    scheduler_gamma: 0.5
    weight_init: None    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02 
    auto_encoder_networks:
      in_channels: 1
      out_channels: 64
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  vae:
    model_filepath: src/models/vae.py
    model_class: VAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l2,kl" #additional loss names
    lr: 0.0001
    criterion: MSE
    kl_weight: 0.0001 #0.00001 #1e-4
    reconst_weight: 1 #1
    scheduler_step_size: 300
    scheduler_gamma: 0.5
    latent_space_size: 16384
    weight_init: None    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    auto_encoder_networks:
      in_channels: 1
      out_channels: 32
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64

evaluation:
  ckpt_path: #Path of saved parameters
