# This file contains all the configuration our different project components
# Add configurations as needed

training:
  name: pvqVAE
  description: plzWork
  experiment_id: pvqVAE-Dev # None | A unique id identifying the experiment folder
  #experiment_id: None
  extra_notes: none
  logs_dir: logs
  is_train: true
  device: cuda:0
  batch_size: 4
  num_workers: 16
  test_size: 0.1
  n_epochs: 50000
  append_loss_every: 50
  print_every: 10
  validate_every: 1480
  save_every: 1480
  save_every_nepochs: 5
  start_epoch: 0
  start_iteration: 0
  visualize_every: 200
  apply_metrics_every: 1480
  load_ckpt: True
  #ckpt_path: logs/0.2ClampFullTraining/NOKL-SamplingApplied/2024_05_17_23_36_33/checkpoints/epoch-20.ckpt
  #ckpt_path: logs/0.2ClampFullTrainingSmallLatentSpace/KL-SamplingAppliedContinueEpoch20FrozenEncoder/2024_05_18_13_00_25/checkpoints/epoch-2.ckpt
  #ckpt_path: logs/vaeTrain/fullyConv/2024_05_17_04_07_52/checkpoints/epoch-60.ckpt
  #ckpt_path: logs/overFitSmallTraining/2048OverfitKL/2024_05_18_14_59_08/checkpoints/epoch-2000.ckpt
  #ckpt_path: logs/2048vaeTrain/204NoKLSampling/2024_05_18_15_25_03/checkpoints/epoch-16.ckpt
  #ckpt_path: logs/2048vaeTrain/2040KLSamplingSmallKLLearningRate/2024_05_18_21_34_36/checkpoints/epoch-18.ckpt
  #ckpt_path: logs/512vaeTrain/512LinearFUllTraining/2024_05_19_00_21_10/checkpoints/epoch-118.ckpt
  #ckpt_path: logs/32*8*8*8vaeTrain/4*8*8*8TrainNoKLTraining/2024_05_19_23_53_19/checkpoints/epoch-50.ckpt
  #ckpt_path: logs/32*8*8*8vaeTrain/2*8*8*8TrainWithNormalizedKLScheduler64^3/2024_05_20_12_59_38/checkpoints/epoch-24.ckpt
  #ckpt_path: logs/exploringKLWeights/2*8*8**Sampling+25KLWeight/2024_05_20_21_35_25/checkpoints/epoch-16.ckpt
  #ckpt_path: logs/VaeTry2/8*8*8**FullTrain/2024_05_21_03_41_13/checkpoints/epoch-74.ckpt
 # ckpt_path: logs/vaePlzWork/32chTrainL1LossSum/2024_05_23_19_42_30/checkpoints/epoch-32.ckpt
  #ckpt_path: logs/vaeLogs/2048LinFullTraining/2024_05_25_17_24_55/checkpoints/epoch-26.ckpt
  ckpt_path: logs/pvqVAE/pvqVAE-Train/2024_05_26_02_46_01/checkpoints/epoch-114.ckpt # Very Important
  use_scheduler: True
  apply_metrics_batch_count: 5 # number of batches to apply additional metrics on
#2024_05_16_20_23_24 id
dataset:
  dataset_field: shape_net_code
  path: ../../datasets/shapenet_orig/ShapeNetCore.v2  # For local testing without downloading shape => change to local_raw_dataset/ShapeNet
    # Can be overriden by dataset specific path
  overfit_size: 1
  split: train # train | valid | test
  is_overfit: False

  shape_net_vox:
    class_filepath: src/datasets/shape_net/shape_net_vox.py
    class: ShapeNetVox
    category: airplane
    path: src/local_raw_dataset/ShapeNet/ShapeNetVox32

  shape_net_points:
    class_filepath: src/datasets/shape_net/shape_net_points.py
    class: ShapeNetPoints
    category: airplane
    path: src/raw_dataset/ShapeNet/ShapeNetPointClouds
  
  shape_net_sdf:
    category: chair
    path: src/raw_dataset/ShapeNetV2/sdf_064
    class_filepath: datasets/shape_net/shape_net_sdf.py
    class: ShapeNetSDF

  shape_net_v2_sdf:
    class_filepath: src/datasets/shape_net/shape_net_v2_sdf.py
    class: ShapeNetV2SDF
    category: chair
    #path:  ../../datasets/shapenet_orig/ShapeNetCore.v2
    path: src/raw_dataset/shapenet_orig
  
  shape_net_v3_sdf:
    class_filepath: src/datasets/shape_net/shape_net_v3_sdf.py
    class: ShapeNetV3SDF
    category: chair
    path: src/raw_dataset/ShapeNetDISN/SDF_v1_64
  
  shape_net_code:
    class_filepath: src/datasets/shape_net/shape_net_code.py
    class: ShapeNetCode
    category: chair
    path: src/raw_dataset/ShapeNetDISN/SDF_v1_64

model:
  model_field: pvqvae
  dummy_classifier:
    model_filepath: models/dummy_classifier.py
    model_class: DummyClassifier
    lr: 0.01
    criterion: CE
    scheduler_step_size: 25
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1
  
  auto_encoder:
    model_filepath: src/models/auto_encoder.py
    model_class: AutoEncoder
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    lr: 0.001
    losses: None
    criterion: MSE
    scheduler_step_size: 300
    scheduler_gamma: 0.5
    weight_init: None    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02 
    auto_encoder_networks:
      in_channels: 1
      out_channels: 64
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  vae:
    model_filepath: src/models/vae.py
    model_class: VAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l2,kl" #additional loss names
    lr: 1.0e-4
    criterion: L1
    base_kl_weight: 0
    reconst_weight: 1 #1
    scheduler_step_size: 300
    scheduler_gamma: 0.5
    cycle_iter: 20000
    stop_cycle_count: 1
   #stop_cycle_count: 1
    weight_init: normal    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    auto_encoder_networks:
      in_channels: 1
      out_channels: 32
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64

  vae3d:
    vae:
    model_filepath: src/models/vae3D.py
    model_class: VAE3D
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l2,kl" #additional loss names
    lr: 1.0e-3
    criterion: L1
    base_kl_weight: 0
    reconst_weight: 1 #1
    scheduler_step_size: 300
    scheduler_gamma: 0.5
    cycle_iter: 20000
    stop_cycle_count: 1
   #stop_cycle_count: 1
    weight_init: normal    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    auto_encoder_networks:
      in_channels: 1
      out_channels: 64
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  pvqvae:
    model_filepath: src/models/pvqvae.py
    model_class: PVQVAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l1,codebook" #additional loss names
    lr: 1.0e-4
    criterion: L1
    scheduler_step_size: 50
    scheduler_gamma: 0.5
    weight_init: normal    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    embed_dim: 256
    n_embed: 512
    auto_encoder_networks:
      in_channels: 1
      out_channels: 64
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  decoder_transformer:
    model_filepath: src/models/pvqvae.py
    model_class: PVQVAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l1,codebook" #additional loss names
    lr: 1.0e-4
    criterion: L1
    scheduler_step_size: 30
    scheduler_gamma: 0.9

    embed_dim: 768
    n_tokens: 512
    n_head: 12
    n_layers_enc: 12
    d_mlp: 256
    dropout: 0.1
    pvqvae:
      embed_dim: 256
      n_embed: 512
    p_encoding:
      init_factor: 10
      pos_dim: 3
      zq_dim: 8
      pos_embed_dim: 128


evaluation:
  ckpt_path: #Path of saved parameters
