# This file contains all the configuration our different project components
# Add configurations as needed

training:
  name: dev
  description: plz
  experiment_id: FullTrainG1.0-2
  ##experiment_id: None
  extra_notes: none
  logs_dir: v2logs
  is_train: true
  device: cuda:0
  batch_size: 4
  num_workers: 16
  test_size: 0.1
  n_epochs: 50000
  append_loss_every: 250
  print_every: 10
  validate_every: 203300000000000000000000000000000000000000
  save_every: 2033000000000000000000000000000000000
  save_every_nepochs: 500000000000000000000000000
  start_epoch: 0
  start_iteration: 0
  visualize_every: 100
  apply_metrics_every: 2033
  use_scheduler: True
  apply_metrics_batch_count: 5 # number of batches to apply additional metrics on
  load_ckpt: False
  ckpt_path: v2logs/globalPVQVAELPIPS/FullTrain/2024_07_20_22_29_31/checkpoints/epoch-50.ckpt
#2024_05_16_20_23_24 id
dataset:
  dataset_field: shape_net_v2_sdf
  path: ../../datasets/shapenet_orig/ShapeNetCore.v2  # For local testing without downloading shape => change to local_raw_dataset/ShapeNet
    # Can be overriden by dataset specific path
  overfit_size: 4
  split: train # train | valid | test
  is_overfit: True

  shape_net_vox:
    class_filepath: src/datasets/shape_net/shape_net_vox.py
    class: ShapeNetVox
    category: airplane
    path: src/local_raw_dataset/ShapeNet/ShapeNetVox32

  shape_net_points:
    class_filepath: src/datasets/shape_net/shape_net_points.py
    class: ShapeNetPoints
    category: airplane
    path: src/raw_dataset/ShapeNet/ShapeNetPointClouds
  
  shape_net_sdf:
    category: chair
    path: src/raw_dataset/ShapeNetV2/sdf_064
    class_filepath: datasets/shape_net/shape_net_sdf.py
    class: ShapeNetSDF

  shape_net_v2_sdf:
    class_filepath: src/datasets/shape_net/shape_net_v2_sdf.py
    class: ShapeNetV2SDF
    category: chair
    #path:  ../../datasets/shapenet_orig/ShapeNetCore.v2
    #path: src/raw_dataset/shapenet_orig
    path: ../../datasets/shapenet_orig/ShapeNetCore.v2
  
  shape_net_v3_sdf:
    class_filepath: src/datasets/shape_net/shape_net_v3_sdf.py
    class: ShapeNetV3SDF
    category: chair
    path: src/raw_dataset/ShapeNetDISN/SDF_v1_64
  
  shape_net_code:
    class_filepath: src/datasets/shape_net/shape_net_code.py
    class: ShapeNetCode
    category: chair
    path: src/raw_dataset/ShapeNetDISN/SDF_v1_64

model:
  model_field:  globalPVQVAE
  dummy_classifier:
    model_filepath: models/dummy_classifier.py
    model_class: DummyClassifier
    lr: 0.01
    criterion: CE
    scheduler_step_size: 25
    scheduler_gamma: 0.5
    dummy_network:
      kernel_size: 3
      padding: 1
  
  auto_encoder:
    model_filepath: src/models/auto_encoder.py
    model_class: AutoEncoder
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    lr: 1.0e-4
    losses:
    criterion: L1
    scheduler_step_size: 30
    scheduler_gamma: 0.5
    weight_init: None    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02 
    auto_encoder_networks:
      in_channels: 1
      out_channels: 256
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  vae:
    model_filepath: src/models/vae.py
    model_class: VAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l1,kl,kl_weight" #additional loss names
    lr: 1.0e-4
    criterion: L1
    base_kl_weight: 3.5e-4
    reconst_weight: 1 #1
    scheduler_step_size: 30000
    scheduler_gamma: 0.5
    cycle_iter: 7500
    stop_cycle_count: 60000
    weight_init: None    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    use_cycles: False
    z_dim: 128
    auto_encoder_networks:
      in_channels: 1
      out_channels: 512
      ch_mult: [1, 2, 2, 4, 8]
      num_res_blocks: 1
      attn_resolutions: [4,8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64

  vae3d:
    vae:
    model_filepath: src/models/vae3D.py
    model_class: VAE3D
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l1,kl,kl_weight,mu_mean,mu_var" #additional loss names
    lr: 1.0e-4
    criterion: L1
    base_kl_weight: 0
    reconst_weight: 1.0 #1
    scheduler_step_size: 50
    scheduler_gamma: 0.5
    cycle_iter: 20000
    stop_cycle_count: 1
    use_kl: False
    use_cycles: False
   #stop_cycle_count: 1
    weight_init: xavier   #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    auto_encoder_networks:
      in_channels: 1
      out_channels: 32
      ch_mult: [1, 2, 2,2, 2]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  pvqvae:
    model_filepath: src/models/pvqvae.py
    model_class: PVQVAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l1,codebook" #additional loss names
    lr: 1.0e-4
    criterion: L1
    scheduler_step_size: 50
    scheduler_gamma: 0.5
    weight_init: normal    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    embed_dim: 256
    n_embed: 512
    auto_encoder_networks:
      in_channels: 1
      out_channels: 256
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  
  decoder_transformer:
    model_filepath: src/models/random_transformer.py
    model_class: RandTransformer
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses:
    lr: 1.0e-4
    criterion: L1
    scheduler_step_size: 70
    scheduler_gamma: 0.9
    weight_init: None
    embed_dim: 768
    n_tokens: 512
    n_head: 12
    n_layers_enc: 12
    d_mlp: 256
    dropout: 0.1
    pvqvae:
      embed_dim: 256
      n_embed: 512
      #ckpt_path: logs/pvqVAE/pvqVAE-Train/2024_05_26_02_46_01/checkpoints/epoch-114.ckpt
      #ckpt_path: logs/GlobalPVQVAE/FullTrain/2024_06_03_12_37_19/checkpoints/epoch-latest.ckpt
      ckpt_path: logs/globalPVQVAEVGGDisc/LinearDiscExp3G1.0e-2@25kBoth/2024_07_10_19_13_37/checkpoints/epoch-best.ckpt
    p_encoding:
      init_factor: 10
      pos_dim: 3
      zq_dim: 8
      pos_embed_dim: 128
  
  globalPVQVAE:
    model_filepath: src/models/global_pvqvae.py
    model_class: GlobalPVQVAE
    metrics: iou,chamferDistance   # None | iou | chamferDistance
    losses: "l1,codebook,p,disc_factor,g_loss,d_weight,disc_loss,logits_real,logits_fake" #additional loss names
    lr: 1.0e-4
    #lr: 0.5e-4
    disc_lr: 4.5e-6
    criterion: L1
    scheduler_step_size: 30
    scheduler_gamma: 0.5
    weight_init: normal    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    embed_dim: 256
    n_embed: 512
    vgg_ckpt: logs/VGG/trainFull/2024_07_01_17_50_17/checkpoints/epoch-36.ckpt
    disc_weight: 1.0e-2
    perceptual_weight: # 0 | 0.5
    disc_start: 15001
    use_disc: True
    auto_encoder_networks:
      in_channels: 1
      out_channels: 256
      ch_mult: [1, 2, 2, 4]
      num_res_blocks: 1
      attn_resolutions: [8]
      dropout: 0.0
      resamp_with_conv: true
      resolution: 64
  


  vgg:
    model_filepath: src/models/vgg19.py
    model_class: VGG16
    metrics: None   # None | iou | chamferDistance
    losses: "acc" #additional loss names
    lr: 1.0e-3
    criterion: CE
   #stop_cycle_count: 1
    weight_init: normal    #None | normal | xavier | xavier_uniform | kaiming | orthogonal
    gain: 0.02
    scheduler_step_size: 30
    scheduler_gamma: 0.5




evaluation:
  ckpt_path: #Path of saved parameters
